### ISSUE TITLE
Crate Name Availability

### ISSUE THREAD

**Issue by berzanorg** [sporto/run-rust#1]
Hi! I'm currently working on a CLI tool to help developers to manage their scripts. It can also import scripts in `package.json`. I'd like to know if you liked the idea behind, and you would mind giving `run` name on crates.io. People will be able to install it by typing `cargo install run`, if you do so. I will also implement a few missing features before launching the tool. The repo is [here](https://github.com/BerzanXYZ/run). Greetings from Berzan.

**Comment by sporto** [comment]
Yeah, happy to give this away, as I don't have any plans for this
